default: &default
  adapter: postgresql
  username: <%= ENV.fetch('DATABASE_USERNAME') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>
  host: <%= ENV.fetch('DATABASE_HOST') %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: gemsavvy_development
