admin:
  max_resources_listed: 250

categories:
  default_name: 'Unknown'

gempackages:
  by_category_min_threshold: 2
  outsiders_stargazers_min_threshold: 200
  outsiders_stargazers_max_threshold: 1000
  outsiders_max_threshold: 50
  outsiders_usage_percentage_threshold: 10

meta_tags:
  description: |
    Our purpose is to provide a simple tool that enables local Ruby
    communities to compare the gems they're using & discover new ones.
  image: gemsavvy-meta
  title: gemsavvy - Share your jewels with your community
  twitter_account: _rubynord

surveys:
  default_timespan_in_days: 30

team:
  -
    avatar: anthony.jpeg
    bio: Code machine
    github: alaibe
    name: Anthony Laibe
    twitter: a_laibe
    website: https://github.com/alaibe
  -
    avatar: cecile.jpeg
    bio: Clean code psychotic
    github: cveneziani
    name: Cecile Veneziani
    twitter: cecilitse
    website: http://cecilitse.org/
  -
    avatar: keuvain.jpeg
    bio: Design patterns master
    github: kdisneur
    name: Kevin Disneur
    twitter: kdisneur
    website: https://kevin.disneur.me/
  -
    avatar: michael.jpeg
    bio: Design magician
    github: lovekaizen
    name: Michael Fatoki-Bello
    twitter: lovekaizen
    website: http://www.lovekaizen.com/
