admin:
  max_resources_listed: 250

categories:
  default_name: 'Unknown'

demo:
  group:
    slug: 'red-miners'
  survey:
    code: '823b8ad1d2a28b'

gempackages:
  by_category_min_threshold: 2
  outsiders_stargazers_min_threshold: 200
  outsiders_stargazers_max_threshold: 1000
  outsiders_max_threshold: 50
  outsiders_usage_percentage_threshold: 10

mailer:
  from: 'hello@ruby-nord.org'

meta_tags:
  short_description: gemsavvy is an awesome new way to share your Ruby trade tools with your community.
  long_description: |
    gemsavvy is an awesome new way to share your Ruby trade tools with your community.
    Plus a chance to discover potential new gems to optimise your workflow, solve problems,
    or even spark debates with fellow developers. How savvy is your gem collection?
    Why not, upload your gemfile to find out.
  image: gemsavvy-meta.jpg
  title: gemsavvy - Share your jewels with your community
  twitter_account: _rubynord

rails_rumble:
  group:
    name: 'Rails Rumble'
    manager_email: 'hello@ruby-nord.org'
    manager_token: 'f9706ae6c647725847d3'
    website_url: 'http://railsrumble.com/'
    slug: 'rails-rumble'
  survey:
    closing_on: '2015-11-30'
    code: 'd4059b37881b6e'
    description: 'Gemfiles Analysis of 2015 Rails Rumble participants'
    name: 'Rails Rumble - Gem surveys 2015'

surveys:
  default_timespan_in_days: 30

team:
  -
    avatar: anthony.jpg
    bio: Code machine
    github: alaibe
    name: Anthony Laibe
    twitter: a_laibe
    website: https://github.com/alaibe
  -
    avatar: cecile.jpg
    bio: Clean code psychotic
    github: cveneziani
    name: Cecile Veneziani
    twitter: cecilitse
    website: http://cecilitse.org/
  -
    avatar: keuvain.jpg
    bio: Design patterns master
    github: kdisneur
    name: Kevin Disneur
    twitter: kdisneur
    website: https://kevin.disneur.me/
  -
    avatar: michael.jpg
    bio: Design magician
    github: lovekaizen
    name: Michael Fatoki-Bello
    twitter: lovekaizen
    website: http://www.lovekaizen.com/
